name: Kernel Build

on:
  workflow_dispatch:
    inputs:
      toolchain:
          description: 'Write toolchain name gcc/clang'
          required: true
      pushto:
          description: 'Send kernel file to github/telegram'
          required: true

env:
  TELEGRAM_TOKEN: ${{ secrets.TG_TOKEN }}
  TELEGRAM_CHAT: ${{ secrets.TG_CHAT }}
  COMP: ${{ github.event.inputs.toolchain }}
  SEND_TO: ${{ github.event.inputs.pushto }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/neutron-projects/docker-image:arch-neutron
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Start building kernel
        run: |
             git clone https://Hoppless:$GH_TOKEN@github.com/KuroSeinenbutV2/Quantum-Electro kernel
             cp kernel.sh kernel
             cp import-ksu.sh kernel
             cd kernel && bash kernel.sh
